### ISSUE TITLE
ABetterBrowser banner is not (or only intermittently) displayed for IE8

### ISSUE THREAD

**Issue by bdzpete** [cloudflare-apps/a-better-browser#68]
CloudFlare support suggested I report this to you.

I defined the CloudFlare aBetterBrowser app for IE 8.0 and below, and tested it from an IE8 browser on Wndows XP.  Although the <HEAD> section of the source code for a very simple html reply includes the abetterbrowser script, the black abetterbrowser banner is not displayed.  The following screenshot, taken 3+ weeks ago, includes page source, rendered page, and proof of IE8.  Repeating the display today gives the same result.

![abetterbrowser banner does not display](https://cloud.githubusercontent.com/assets/13046358/8351154/0e47808c-1b23-11e5-9ee6-69473bd5f329.jpg)

You can test this yourself by visiting website www.abtuk.org.uk for which the abetterbrowser CloudFlare app is, and will remain, enabled for IE8 and below.  The black abetterbrowser banner is not displayed.  This website has only 1 page, containing a single link (a clickable image).  

Further: If that link is clicked, this takes the visitor to multi-page website www.biodanza4me.com which is in the same CloudFlare account and for which the abetterbrowser app is also enabled for IE8 and below.  The black abetterbrowser banner appears intermittently on the pages of this website - I have not yet been able to discern a pattern for the [non-]display of the banner.

During all my testing I did not click the link in the black abetterbrowser banner, nor did I click the big X (to dismiss it).

Regards,
Pete

**Comment by xPaw** [comment]
I'm seeing these errors in console:
```
SCRIPT5007: Unable to get property 'toString' of undefined or null reference
rocket.js (4,13223)
```

CloudFlare's rocket loader could be failing?

**Comment by bdzpete** [comment]
Thanks for the quick response.

I have de-activated Rocket Loader and re-tested.  IE Developer Tools | Network shows that file rocket.js is no longer downloaded, and within the html source the var CloudFlare= string now contains rocket:"0" (previously was rocket:"a").  However the black abetterbrowser banner is still not displayed.  Please try it yourself.

**Comment by xPaw** [comment]
It seems like `CloudFlare.define` promise is not actually being fired, so the code is never executed. Could you tell CF support to get one of their engineers to take a look?

**Comment by bdzpete** [comment]
I have passed this back to CloudFlare (in their ticket number 436010).  I will let you know their response.

**Comment by exegete** [comment]
Did CloudFlare get back to you on ticket #436010, bdzpete? I, too, am having issues with A Better Browser.

**Comment by bdzpete** [comment]
Hi,
On 26 July I updated my CloudFlare ticket #436010 with the following text:    One month on: Has there been any progress on resolving this?

CloudFlare have not yet responded.  But historically I've found that although CloudFlare first-line support are fairly good at responding, once a topic gets passed back to their developers there is rarely further feedback (whether to say "fixed" or to say "no change planned - working as designed").  This may not be justified comment for CloudFlare's paying customers, but it is certainly true for my cost-free basic account.
Just a thought: since A Better Browser is the first App listed the the CloudFlare "Apps" section, I would have thought it would be in their own interests to ensure that it integrates effectively with CF (it would be bad PR otherwise, for both them and you).  As the app developer, you probably have more influence than a non-paying customer like me has with the CF developers.  Can I suggest you contact them directly?
Regards,Pete Simpson

**Comment by pencoyd** [comment]
I work at CloudFlare. The report has been acknowledged and is being examined by one of the developers of the loader script responsible.

John

**Comment by exegete** [comment]
Thank you, John.

Once the examination is complete, is it possible to update us here?

**Comment by Jip-Hop** [comment]
I hope a solution comes for this problem. I experience the same (the warning banner not showing) in IE 11. It's working fine in Chrome and Safari. I'm also using CloudFlare with Rocket Loader, but turning off Rocker Loader doesn't change anything.

**Comment by xPaw** [comment]
I think this might no longer be a problem with the app system that Cloudflare has.
