### ISSUE TITLE
Linked whatbrowser.org is broken in IE < 10

### ISSUE THREAD

**Issue by acdha** [cloudflare-apps/a-better-browser#72]
I don't know if you have contacts at Google but whatbrowser.org does not render in Internet Explorer versions before 10 due to a console call left in by mistake:

http://www.webpagetest.org/result/151015_SY_15PT/1/screen_shot/

That always fails in IE 7 and earlier and breaks in IE 8 and 9 _except_ when the developer tools are open.

**Comment by tomByrer** [comment]
Do you have an extra local copy of the screenshot handy @acdha ?

**Comment by acdha** [comment]
Here's what it looks like in IE8:

http://www.webpagetest.org/screen_shot.php?test=160411_KZ_11RH&run=2&cached=0

IE11:

http://www.webpagetest.org/result/160411_GJ_11S1/

Here's a bunch of different versions:

https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/#http://whatbrowser.org

**Comment by SnakeDoc** [comment]
Same issue here. Preventing us from using this app. We specifically need to detect IE8 and older, but we get exactly what @acdha has in his screenshots.

**Comment by xPaw** [comment]
I've switched to browsehappy.com, hopefully I can push an update soon.
