### ISSUE TITLE
Windows 10 Microsoft Edge 39.14986.1000.0

### ISSUE THREAD

**Issue by skydivematy** [cloudflare-apps/a-better-browser#75]
Hi, i have in my Cloudflare  "A Better Browser" setup for Windows Browser Highest version "10". Running the site on Windows 10 Microsoft Edge 39.14986.1000.0, A Better Browser recognize Edge as old Browser...

Thank you..

**Comment by BamaStangGuy** [comment]
Same issue seen here.

**Comment by aikq35** [comment]
Very good

**Comment by jdalton** [comment]
The configuration was probably set up wrong. Edge has two version numbers. One for the app container (the high 30+ version number) and then one for the platform (the 14-16 version number). You should be using the platform version number.
