### ISSUE TITLE
whatbrowser.org replacement

### ISSUE THREAD

**Issue by xPaw** [cloudflare-apps/a-better-browser#81]
"This website will be unavailable after November 30, 2018."

@TeffenEllis Have any ideas?

**Comment by TeffenEllis** [comment]
Hi Pavel,

I'm no longer with Cloudflare and won't be able make any changes to this repo. Perhaps https://www.whatsmybrowser.org/ may be a good replacement link.

**Comment by xPaw** [comment]
That site doesn't suggest upgrading.

However https://browsehappy.com looks like a good alternative.
